package mybatis.pojo;

import java.util.Date;

public class EmpAll {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp.id
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp.emp_id
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    private Integer empId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp.emp_name
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    private String empName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp.gender
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp.identity
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    private String identity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp.degree
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    private String degree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp.working
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    private String working;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp.department
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp.job
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    private String job;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp.onboarding
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    private Date onboarding;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp.dimission
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    private Date dimission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp.phone
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp.email
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp.phone_id
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    private Integer phoneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp.group_id
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp.address
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp.school
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    private String school;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp.profession
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    private String profession;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp.birth
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    private Date birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp.age
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    private Integer age;

    @Override
    public String toString() {
        return "EmpAll{" +
                "id=" + id +
                ", empId=" + empId +
                ", empName='" + empName + '\'' +
                ", gender='" + gender + '\'' +
                ", identity='" + identity + '\'' +
                ", degree='" + degree + '\'' +
                ", working='" + working + '\'' +
                ", department='" + department + '\'' +
                ", job='" + job + '\'' +
                ", onboarding=" + onboarding +
                ", dimission=" + dimission +
                ", phone='" + phone + '\'' +
                ", email='" + email + '\'' +
                ", phoneId=" + phoneId +
                ", groupId=" + groupId +
                ", address='" + address + '\'' +
                ", school='" + school + '\'' +
                ", profession='" + profession + '\'' +
                ", birth=" + birth +
                ", age=" + age +
                '}';
    }

    public EmpAll(Integer id, Integer empId, String empName, String gender, String identity, String degree, String working, String department, String job, Date onboarding, Date dimission, String phone, String email, Integer phoneId, Integer groupId, String address, String school, String profession, Date birth, Integer age) {
        this.id = id;
        this.empId = empId;
        this.empName = empName;
        this.gender = gender;
        this.identity = identity;
        this.degree = degree;
        this.working = working;
        this.department = department;
        this.job = job;
        this.onboarding = onboarding;
        this.dimission = dimission;
        this.phone = phone;
        this.email = email;
        this.phoneId = phoneId;
        this.groupId = groupId;
        this.address = address;
        this.school = school;
        this.profession = profession;
        this.birth = birth;
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp.id
     *
     * @return the value of t_emp.id
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp.id
     *
     * @param id the value for t_emp.id
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp.emp_id
     *
     * @return the value of t_emp.emp_id
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp.emp_id
     *
     * @param empId the value for t_emp.emp_id
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp.emp_name
     *
     * @return the value of t_emp.emp_name
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp.emp_name
     *
     * @param empName the value for t_emp.emp_name
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp.gender
     *
     * @return the value of t_emp.gender
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp.gender
     *
     * @param gender the value for t_emp.gender
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp.identity
     *
     * @return the value of t_emp.identity
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    public String getIdentity() {
        return identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp.identity
     *
     * @param identity the value for t_emp.identity
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    public void setIdentity(String identity) {
        this.identity = identity == null ? null : identity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp.degree
     *
     * @return the value of t_emp.degree
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    public String getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp.degree
     *
     * @param degree the value for t_emp.degree
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    public void setDegree(String degree) {
        this.degree = degree == null ? null : degree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp.working
     *
     * @return the value of t_emp.working
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    public String getWorking() {
        return working;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp.working
     *
     * @param working the value for t_emp.working
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    public void setWorking(String working) {
        this.working = working == null ? null : working.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp.department
     *
     * @return the value of t_emp.department
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp.department
     *
     * @param department the value for t_emp.department
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp.job
     *
     * @return the value of t_emp.job
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp.job
     *
     * @param job the value for t_emp.job
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp.onboarding
     *
     * @return the value of t_emp.onboarding
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    public Date getOnboarding() {
        return onboarding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp.onboarding
     *
     * @param onboarding the value for t_emp.onboarding
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    public void setOnboarding(Date onboarding) {
        this.onboarding = onboarding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp.dimission
     *
     * @return the value of t_emp.dimission
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    public Date getDimission() {
        return dimission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp.dimission
     *
     * @param dimission the value for t_emp.dimission
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    public void setDimission(Date dimission) {
        this.dimission = dimission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp.phone
     *
     * @return the value of t_emp.phone
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp.phone
     *
     * @param phone the value for t_emp.phone
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp.email
     *
     * @return the value of t_emp.email
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp.email
     *
     * @param email the value for t_emp.email
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp.phone_id
     *
     * @return the value of t_emp.phone_id
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    public Integer getPhoneId() {
        return phoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp.phone_id
     *
     * @param phoneId the value for t_emp.phone_id
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    public void setPhoneId(Integer phoneId) {
        this.phoneId = phoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp.group_id
     *
     * @return the value of t_emp.group_id
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp.group_id
     *
     * @param groupId the value for t_emp.group_id
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp.address
     *
     * @return the value of t_emp.address
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp.address
     *
     * @param address the value for t_emp.address
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp.school
     *
     * @return the value of t_emp.school
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp.school
     *
     * @param school the value for t_emp.school
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp.profession
     *
     * @return the value of t_emp.profession
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    public String getProfession() {
        return profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp.profession
     *
     * @param profession the value for t_emp.profession
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    public void setProfession(String profession) {
        this.profession = profession == null ? null : profession.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp.birth
     *
     * @return the value of t_emp.birth
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp.birth
     *
     * @param birth the value for t_emp.birth
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    public void setBirth(Date birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp.age
     *
     * @return the value of t_emp.age
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp.age
     *
     * @param age the value for t_emp.age
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    public void setAge(Integer age) {
        this.age = age;
    }
}