package mybatis.mapper;

import java.util.List;
import mybatis.pojo.EmpAll;
import mybatis.pojo.EmpAllExample;
import org.apache.ibatis.annotations.Param;

public interface EmpAllMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    int countByExample(EmpAllExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    int deleteByExample(EmpAllExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    int insert(EmpAll record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    int insertSelective(EmpAll record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    List<EmpAll> selectByExample(EmpAllExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    EmpAll selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    int updateByExampleSelective(@Param("record") EmpAll record, @Param("example") EmpAllExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    int updateByExample(@Param("record") EmpAll record, @Param("example") EmpAllExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    int updateByPrimaryKeySelective(EmpAll record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Fri Jul 22 11:54:52 CST 2022
     */
    int updateByPrimaryKey(EmpAll record);
}